### PR TITLE
Adds acceldecel handling for Locator

### PR DESCRIPTION
**Pull request by emilymdubois**
Refs [issue #8](https://github.com/mapbox/guidance-replay/issues/8)

This PR tracks the addition of:
- Better locator handling when `{"spacing": "acceldecel"}`, specifically in modifying the times at which maneuvers are expected to occur
- Tests for `{"spacing": "acceldecdel"}` mode

@emilymcafee @yhahn can I borrow your 👀?

### CODE REVIEW

**Comment by emilymcafee** [comment]
Looks good @emilymdubois - the only thing I would flag is the value of `rate` here:

``` js
var interpolate = interpolateAccelDecel(steps, 5);
```

⚠️ point of future confusion:

We're using this 5 [elsewhere too](https://github.com/mapbox/guidance-replay/blob/803765a01c19af20e73235574bf74ee4f9c541b5/lib/route.js#L113) because... it's not immediately obvious what this value should be - what kind of car are you driving? how maniacal/cautious are you? also this probs changes at different speeds? Being smart about `rate` is _defs_ a different quest, but now that we're relying on this in multiple locations, let's future-proof and make sure it's not hard-coded anywhere. Options:
1. Do you think it's easy to pull this out and make it a configurable parameter somewhere along the way?
2. Or, the opposite - we could bake the 5 into [this function](https://github.com/mapbox/guidance-replay/blob/803765a01c19af20e73235574bf74ee4f9c541b5/lib/route.js#L172) once  (this is probs the easier route & I feel good about that)

**Comment by emilymdubois** [comment]
:wave: @emilymcafee, thanks for the feedback! I think I also prefer option #2 from a readability standpoint. If we were to make `rate` a configurable parameter, I think we would have to pass it through the `options` object [in the `route()` function](https://github.com/mapbox/guidance-replay/blob/803765a01c19af20e73235574bf74ee4f9c541b5/lib/route.js#L24), which seems a little high-level for an esoteric parameter that I think we can make a reasonable assumption about author-side.

**Comment by emilymdubois** [comment]
@emilymcafee I added a little functionality to export a `coordinates <=> times` mapping for maneuvers for use in instructional countdowns [`directions-sim` issue #15](https://github.com/mapbox/directions-sim/issues/15). I added the `Locator.maneuvers()` function for this purpose and tests in the last (`00bee0f`) commit.

Let me know if everything looks 👌  to you!

**Comment by emilymcafee** [comment]
@emilymdubois cool, so `Locator.maneuvers()` returns time & location (possibly adjusted bc of accel/decel) of each maneuver along the route? Nice 👌 

Looks good to 🚢  when you're ready!

**Comment by emilymdubois** [comment]
@emilymcafee correct about the `Locator.maneuvers()` function! It'll allow for us to look at countdowns to the next maneuver in terms of time instead of distance 😍 

Merging!

**Pull request merged**
